source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
link_with 'Fresco2 WatchKit Extension', 'Fresco2'
#pod 'CMPopTipView'
#pod 'Parse'
#pod 'PBWebViewController'

pod 'AFNetworking', '~> 2.1'
pod 'AFNetworkActivityLogger'
# pod 'AFAmazonS3Manager'

pod 'Mantle', '~> 1.3'
pod 'Functional.m', '~> 1.0'
pod 'ASIHTTPRequest', '~> 1.8'
#pod 'TMCache', '~> 1.2'
#pod 'JASidePanels', '~> 1.3'
#pod 'iCarousel', '~> 1.7'
#pod 'Block-KVO', '~> 2.2'
#pod 'CocoaLumberjack', '~> 1.8'
#pod 'UIImage-Resize', '~> 1.0'
#pod 'AAPullToRefresh'
#pod 'Facebook-iOS-SDK' , '~> 3.18.0'
#pod 'GRKGradientView', '~> 1.0'
pod 'Cloudinary'

inhibit_all_warnings!
