source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
link_with 'Fresco WatchKit Extension', 'Fresco'
pod 'STKWebKitViewController'
pod 'SVPullToRefresh'
pod 'AFNetworking', '~> 2.1'
pod 'AFNetworkActivityLogger'
pod 'BTBadgeView'
pod 'SVPulsingAnnotationView'
pod 'Mantle', '~> 1.3'
pod 'Functional.m', '~> 1.0'
pod 'GRKGradientView'
pod 'SVGKit'

inhibit_all_warnings!
